package Hiber;
// Generated 2023-01-25 13:21:25 by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * Ppt generated by hbm2java
 */
public class Ppt  implements java.io.Serializable {


     private int id;
     private String nazwa;
     private Blob dane;
     private String opis;
     
    public Ppt() {
    }

	
    public Ppt(int id) {
        this.id = id;
    }
    public Ppt(int id, String nazwa, Blob dane, String opis) {
       this.id = id;
       this.nazwa = nazwa;
       this.dane = dane;
       this.opis = opis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Blob getDane() {
        return this.dane;
    }
    
    public void setDane(Blob dane) {
        this.dane = dane;
    }

    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }


}


